# Generated by Django 3.2 on 2023-11-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField()),
                ('age', models.IntegerField()),
                ('J_date', models.DateField()),
                ('symptoms', models.CharField(max_length=200)),
                ('prescription', models.CharField(max_length=200)),
            ],
        ),
    ]
